# Generated by Django 5.1.3 on 2024-12-05 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_programmer_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('Sexo', models.CharField(max_length=1)),
                ('Num_Fich', models.IntegerField(max_length=7)),
                ('Formacion', models.BooleanField(default=True)),
                ('Fecha_ingreso', models.DateField(default=None)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
